package:
  name: "delfta"
  version: "0.5"

source:
  path: ../


requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - joblib>=1.0.1
    - matplotlib>=3.3.2
    - numpy>=1.19.2
    - pandas>=1.1.3
    - pip>=20.2.4
    - python
    - scikit-learn>=0.23.2
    - scipy>=1.5.2
    - tqdm>=4.51.0
    - pytorch=1.8.0
    - pytorch-geometric=1.7.2
    - cudatoolkit=10.2  # [linux64 or win64]
    - openbabel>=3.1.1
    - h5py>=3.2.1
    - xtb=6.4.1
    - einops=0.3.0


about:
  home: "https://github.com/josejimenezluna/delfta"
  license: AGPLv3
  license_family: AGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - josejimenezluna
