package:
  name: "delfta"
  version: "1.0.2"

source:
  path: ../


requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python
    - pytorch
    - torch-scatter
    - pytorch_geometric
    - openbabel
    - xtb=6.3.1 # pin for delfta compatibility
    - h5py
    - numpy
    - pandas
    - scikit-learn
    - scipy
    - matplotlib
    - tqdm
    - joblib
    - einops
    - pip
    - pytest 


about:
  home: "https://github.com/josejimenezluna/delfta"
  license: AGPLv3
  license_family: AGPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - josejimenezluna
